<?php

/**
 * PuntoNavegacionPuntoNavegacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PuntoNavegacionPuntoNavegacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PuntoNavegacionPuntoNavegacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PuntoNavegacionPuntoNavegacion');
    }

    public static function retrieveById($global_id){
        $query = Doctrine_Query::create()->
                from('PuntoNavegacionPuntoNavegacion p')->
                where('p.punto_navegacion_1_id = ?',$global_id)->
                orWhere('p.punto_navegacion_2_id = ?',$global_id);

        return $query->fetchArray();
    }
}