<?php

/**
 * PuntosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PuntosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PuntosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Puntos');
    }
    
    static public function getPuntosBy($estructura_id){
      $query = Doctrine_Query::create()->
              from('Puntos p')->
              where('p.estructura_id = ?',$estructura_id);
      $puntos = $query->execute();      
      return $puntos;
    }          
}