# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Indoor Navigation 2D/3D
    description:  Sistema de navegación 2D/3D para interiores
    #keywords:     symfony, project
    language:     es_AR
    #robots:       index, follow

  stylesheets:    [indoor-navigation.css, jquery-ui.css, base.css, jquery.mobile-1.3.0.min.css, info.css]

  javascripts:    [lib/jsqrcode/grid.js, lib/jsqrcode/version.js,lib/jsqrcode/detector.js,lib/jsqrcode/formatinf.js,lib/jsqrcode/errorlevel.js,lib/jsqrcode/bitmat.js,lib/jsqrcode/datablock.js,lib/jsqrcode/bmparser.js,lib/jsqrcode/datamask.js,lib/jsqrcode/rsdecoder.js,lib/jsqrcode/gf256poly.js,lib/jsqrcode/gf256.js,lib/jsqrcode/decoder.js,lib/jsqrcode/QRCode.js,lib/jsqrcode/findpat.js,lib/jsqrcode/alignpat.js,lib/jsqrcode/databr.js,qr.js,camera.js, jquery-1.8.2.min.js, kinetic-v3.10.4.js, kinetic-functions.js, Three.js, Detector.js, Stats.js, OrbitControls.js, THREEx.KeyboardState.js, THREEx.FullScreen.js, THREEx.WindowResize.js, jquery-1.9.1.js, jquery-ui.js, info.js, tween.min.js, jquery.mobile-1.3.0.min.js, activar-camara.js]

  has_layout:     true
  layout:         layout