<?php

/**
 * BaseOrientacionPared
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Doctrine_Collection $ParedDibujable
 * 
 * @method string              getNombre()         Returns the current record's "nombre" value
 * @method Doctrine_Collection getParedDibujable() Returns the current record's "ParedDibujable" collection
 * @method OrientacionPared    setNombre()         Sets the current record's "nombre" value
 * @method OrientacionPared    setParedDibujable() Sets the current record's "ParedDibujable" collection
 * 
 * @package    tesis-recargada
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrientacionPared extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orientacion_pared');
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ParedDibujable', array(
             'local' => 'id',
             'foreign' => 'orientacion_pared_id'));
    }
}