<?php

/**
 * BaseMultimedia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property integer $tipo
 * @property integer $estructura_id
 * @property Doctrine_Collection $Estructura
 * 
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method integer             getTipo()          Returns the current record's "tipo" value
 * @method integer             getEstructuraId()  Returns the current record's "estructura_id" value
 * @method Doctrine_Collection getEstructura()    Returns the current record's "Estructura" collection
 * @method Multimedia          setNombre()        Sets the current record's "nombre" value
 * @method Multimedia          setTipo()          Sets the current record's "tipo" value
 * @method Multimedia          setEstructuraId()  Sets the current record's "estructura_id" value
 * @method Multimedia          setEstructura()    Sets the current record's "Estructura" collection
 * 
 * @package    tesis-recargada
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMultimedia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('multimedia');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tipo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('estructura_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Estructura', array(
             'refClass' => 'Estructura',
             'local' => 'estructura_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}