<?php

/**
 * MultimediaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MultimediaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MultimediaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Multimedia');
    }
    
    static public function getMultimediaPara($estructura_id){
      $query = Doctrine_Query::create()->
              from('Multimedia m')->
              where('m.estructura_id = ?',$estructura_id);
      
      return $query->execute();
    }
}