<?php

/**
 * OrientacionParedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrientacionParedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrientacionParedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrientacionPared');
    }
}