<?php

/**
 * PuntoNavegacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tesis-recargada
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PuntoNavegacion extends BasePuntoNavegacion
{
  /**
   * Función que devuelve el nombre de la estructura, si no existe estructura asociada se devuelve un blanco
   * @return string
   */
  public function getNombreEstructura(){
    if (is_null($this->getEstructuraId()))
      return '';
    return Doctrine::getTable('Estructura')->find($this->getEstructuraId())->getNombre();
  }
}