<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/10/18 02:13:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=indoor_navigation',
  'username' => 'root',
  'password' => 'manuel31042332',
  'name' => 'doctrine',
)),);
