generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           ParedDibujable
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          pared_dibujable
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:    'Listado de Paredes Dibujables'
        display:  [Punto1,Punto2, link_imagen, descripcion,OrientacionPared]
        object_actions:
          _edit: ~
          _delete: ~
      filter:  ~
      form:    ~
      edit:
        title:  'Edición de Pared Dibujable'
      new:
        title: 'Nueva Pared Dibujable'
      show:
        title:    'Ver Pared'
        display:
          Información General: [Punto1, Punto2, link_imagen,descripcion, OrientacionPared]        
      revert:  ~

