<?php

/**
 * BasePuntoNavegacionPuntoNavegacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $punto_navegacion_1_id
 * @property integer $punto_navegacion_2_id
 * @property float $distancia
 * 
 * @method integer                        getPuntoNavegacion1Id()    Returns the current record's "punto_navegacion_1_id" value
 * @method integer                        getPuntoNavegacion2Id()    Returns the current record's "punto_navegacion_2_id" value
 * @method float                          getDistancia()             Returns the current record's "distancia" value
 * @method PuntoNavegacionPuntoNavegacion setPuntoNavegacion1Id()    Sets the current record's "punto_navegacion_1_id" value
 * @method PuntoNavegacionPuntoNavegacion setPuntoNavegacion2Id()    Sets the current record's "punto_navegacion_2_id" value
 * @method PuntoNavegacionPuntoNavegacion setDistancia()             Sets the current record's "distancia" value
 * 
 * @package    tesis-recargada
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePuntoNavegacionPuntoNavegacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('punto_navegacion_punto_navegacion');
        $this->hasColumn('punto_navegacion_1_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('punto_navegacion_2_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('distancia', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}