<?php

/**
 * BaseEstructura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property integer $tipo
 * @property integer $capacidad
 * @property boolean $es_navegable
 * @property Doctrine_Collection $Multimedia
 * @property Doctrine_Collection $Puntos
 * @property Doctrine_Collection $PuntoNavegacion
 * 
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method integer             getTipo()            Returns the current record's "tipo" value
 * @method integer             getCapacidad()       Returns the current record's "capacidad" value
 * @method boolean             getEsNavegable()     Returns the current record's "es_navegable" value
 * @method Doctrine_Collection getMultimedia()      Returns the current record's "Multimedia" collection
 * @method Doctrine_Collection getPuntos()          Returns the current record's "Puntos" collection
 * @method Doctrine_Collection getPuntoNavegacion() Returns the current record's "PuntoNavegacion" collection
 * @method Estructura          setNombre()          Sets the current record's "nombre" value
 * @method Estructura          setTipo()            Sets the current record's "tipo" value
 * @method Estructura          setCapacidad()       Sets the current record's "capacidad" value
 * @method Estructura          setEsNavegable()     Sets the current record's "es_navegable" value
 * @method Estructura          setMultimedia()      Sets the current record's "Multimedia" collection
 * @method Estructura          setPuntos()          Sets the current record's "Puntos" collection
 * @method Estructura          setPuntoNavegacion() Sets the current record's "PuntoNavegacion" collection
 * 
 * @package    tesis-recargada
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstructura extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estructura');
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('tipo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('capacidad', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('es_navegable', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Multimedia', array(
             'refClass' => 'Estructura',
             'local' => 'id',
             'foreign' => 'estructura_id'));

        $this->hasMany('Puntos', array(
             'refClass' => 'Estructura',
             'local' => 'id',
             'foreign' => 'estructura_id'));

        $this->hasMany('PuntoNavegacion', array(
             'refClass' => 'Estructura',
             'local' => 'id',
             'foreign' => 'estructura_id'));
    }
}