<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/10/18 02:13:49
sfConfig::add(array(
  'app_canvas_width' => '600',
  'app_canvas_height' => '500',
  'app_maximo_escala' => '7',
  'app_minimo_escala' => '3',
  'app_maximo_y' => '3800',
  'app_escala' => '5',
  'app_version' => 1.2,
));
