<?php
// auto-generated by sfViewConfigHandler
// date: 2013/10/18 02:13:49
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Indoor Navigation 2D/3D', false, false);
  $response->addMeta('description', 'Sistema de navegación 2D/3D para interiores', false, false);
  $response->addMeta('language', 'es_AR', false, false);

  $response->addStylesheet('indoor-navigation.css', '', array ());
  $response->addStylesheet('base.css', '', array ());
  $response->addStylesheet('jquery-ui.css', '', array ());
  $response->addStylesheet('info.css', '', array ());
  $response->addJavascript('kinetic-v3.10.4.js', '', array ());
  $response->addJavascript('kinetic-functions.js', '', array ());
  $response->addJavascript('Three.js', '', array ());
  $response->addJavascript('Detector.js', '', array ());
  $response->addJavascript('Stats.js', '', array ());
  $response->addJavascript('OrbitControls.js', '', array ());
  $response->addJavascript('THREEx.KeyboardState.js', '', array ());
  $response->addJavascript('THREEx.FullScreen.js', '', array ());
  $response->addJavascript('THREEx.WindowResize.js', '', array ());
  $response->addJavascript('jquery-1.9.1.js', '', array ());
  $response->addJavascript('jquery-ui.js', '', array ());
  $response->addJavascript('info.js', '', array ());


